<?php

define('COMMERCE_SERVICE_URL', 'http://shop.jinbeizeng.com/service/');
define('TOTAL_PAGE', '2');

/**
 * Implements hook_menu().
 */
function cowpro_shop_menu() {
	$items = array ();
	$items ['shop'] = array (
			'title' => '积分商城',
			'description' => '用积分兑换商品',
			'page callback' => 'cowpro_shop_list',
			'access callback' => TRUE,
			//'menu_name' => 'navigation',
			'type' => MENU_NORMAL_ITEM,
			'weight' => 10
	);
	$items ['shop/detail/%'] = array (
			'title' => '积分商城',
			'description' => '用积分兑换商品',
			'page callback' => 'cowpro_shop_detail',
			'page arguments' => array(2),
			'access callback' => TRUE,
			//'menu_name' => 'navigation',
			'type' => MENU_NORMAL_ITEM,
			'weight' => 10
	);
	$items ['shop/buy/%/%'] = array (
			'title' => '兑换',
			'description' => '用积分兑换商品',
			'page callback' => 'cowpro_shop_buy',
			'page arguments' => array(2, 3),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
			'weight' => 10
	);
	$items ['shop/redemption'] = array (
			'title' => '兑现奖金',
			'description' => '兑现奖金',
			'page callback' => 'cowpro_shop_redemption',
			'access callback' => 'user_is_logged_in',
			'type' => MENU_CALLBACK,
	);
	return $items;
}

/**
 * Implements hook_theme().
 */
function cowpro_shop_theme() {
	return array(
			'cowpro_commerce_list' => array(
					'variables' => array('list' => NULL, 'page_html' => NULL),
					'file' => 'cowpro_shop.pages.inc',
					'template' => 'cowpro-commerce-list',
			),
			'cowpro_commerce_list_item' => array(
					'variables' => array('item' => NULL),
					'file' => 'cowpro_shop.pages.inc',
					'template' => 'cowpro-commerce-list-item',
			),
			'cowpro_commerce_item' => array(
					'variables' => array('item' => NULL),
					'file' => 'cowpro_shop.pages.inc',
					'template' => 'cowpro-commerce-item',
			),
	);
}

function cowpro_shop_list($page = 0) {
	$service = new WSClientServiceDescription();
	$service->name = 'commerce-kickstart';
	$service->label = 'commerce kickstart';
	$service->url = COMMERCE_SERVICE_URL;
	$service->type = 'rest';

	$operation = array();
	$operation['label'] = 'Index';
	$operation['url'] = 'entity_node';
	$operation['type'] = 'GET';
	$operation['parameter'] = array();
	$operation['parameter']['page'] = array('type' => 'integer', 'label' => 'Page NO.');
	$operation['parameter']['pagesize'] = array('type' => 'integer', 'label' => 'Page Size');
	$operation['parameter']['sort'] = array('type' => 'text', 'label' => 'Sort');
	$operation['parameter']['direction'] = array('type' => 'text', 'label' => 'Sort Direction');
	//$operation['result'] = array('type' => 'node', 'label' => 'Node');
	$service->operations['index'] = $operation;

	//缓存商品列表
	if ( $cache = cache_get('shop_list_cache_'.$page )) {
		$result = $cache->data;
	}else {
		$result = $service->index($page, 21, 'sticky', 'DESC');
		cache_set('shop_list_cache_'.$page, $result, 'cache', 60 * 60); //1 hour
	}

	$prev_page = $page - 1;
	$prev_page >= 0 ? $prev_page_html = "<a href='/shop/".$prev_page."'>上一页</a>" : $prev_page_html = "";

	$out_html = "<div id='shop_list'><a href='/shop'>首页</a>".$prev_page_html."";
	for( $i = 0; $i <= TOTAL_PAGE; $i++ ) {
		$j = $i + 1;
		if( $i == 0 ) $i = '';
		$out_html .= '<a href="/shop/'.$i.'">'.$j.'</a>';
	}

	$next_page = $page + 1;
	$next_page <= TOTAL_PAGE ? $next_page_html = "<a href='/shop/".$next_page."'>下一页</a>" : $next_page_html = "";

	$out_html .= "".$next_page_html."<a href='/shop/".TOTAL_PAGE."'>尾页</a></div>";
	$html = theme('cowpro_commerce_list', array('list' => $result,'page_html'=>$out_html));

	return $html;
}

function _cowpro_shop_retrieve_detail($nid) {
	$service = new WSClientServiceDescription();
	$service->name = 'commerce-kickstart';
	$service->label = 'commerce kickstart';
	$service->url = COMMERCE_SERVICE_URL;
	$service->type = 'rest';

	$operation = array();
	$operation['label'] = 'retrieve';
	$operation['url'] = 'entity_node/@nid';
	$operation['type'] = 'GET';
	$operation['parameter']['nid'] = array('type' => 'integer', 'label' => 'Node id');
	$operation['result'] = array('type' => 'node', 'label' => 'Node');
	$service->operations['retrieve'] = $operation;
	$result = $service->retrieve($nid);
	return $result;
}

function cowpro_shop_detail($nid) {
	$result = _cowpro_shop_retrieve_detail($nid);
	$key_words_array = array("移动","联通","电信","话费","充值");
	foreach( $key_words_array as $item ){
		!strpos($result['title_original'],$item) ? $result['show_bill_input'] = 0 : $result['show_bill_input'] = 1;
	}
	drupal_set_title($result['title']);
	$html = theme('cowpro_commerce_item', array('item' => $result));

	return $html;
}

function cowpro_shop_buy($nid, $vid) {
	$result = _cowpro_shop_retrieve_detail($nid);
	$found = FALSE;
	$title = NULL;
	$price = NULL;
	foreach ($result['products'] as $p) {
		if ($p['revision_id'] === $vid) {
			$found = TRUE;
			$title = $p['title'];
			$price = $p['commerce_price']['und'][0]['amount'];
			break;
		}
	}

	if (!$found) {
		drupal_set_message('没有找到所需商品！', 'error');
	} else {
		$qty = $_GET['qty'];
		$mbl = @$_GET['mbl'];
		_cowpro_shop_buy_item($nid, $vid, $title, $price, $qty, $mbl);
	}
	$url = $GLOBALS['base_url'] . "/shop/detail/$nid";
	return drupal_goto($url);
}

function _cowpro_shop_buy_item($nid, $vid, $title, $price, $qty, $mbl = NULL) {
	$qty = intval($qty);
	if ($qty <= 0) {
		drupal_set_message('要兑换的商品数量不正确！', 'error');
		return;
	}
	if( !empty($mbl) ) {
		$isMbl = preg_match("/^1[34578]\d{9}$/", $mbl) ? true : false;
		if( !$isMbl ) {
			drupal_set_message('输入的手机号码格式不正确！', 'error');
			return;
		}
	}

	global $user;
	$points = userpoints_get_current_points($user->uid);
	$amount = ($price / 100) * $qty;
	if ($points < $amount) {
		drupal_set_message('积分不足！', 'error');
		return;
	}

	//$tid = _blackhat_leadsdata_get_user_points_tid();
	$user_mobile = db_select('cowpro_customer_profile', 'profile')->fields('profile', array('search_field'))->condition('type', 'mobile')->condition('uid',  $user->uid )->execute()->fetchAssoc();
	$des_mobile = !empty($mbl) ? $mbl : $user_mobile['search_field'];
	$desc = "(数量=$qty;nid=$nid;vid=$vid;手机号码=".$des_mobile.")$title";
	$params = array (
			'uid' => $user->uid,
			'points' => 0-$amount,
			'moderate' => false,
			'description' => $desc,
			'display' => false,
			//'tid' => $tid,
			//'entity_id' => $nid,
			//'entity_type' => 'order',
	);
	$result = userpoints_userpointsapi($params);
	if ($result['status']) {
		drupal_set_message('兑换申请已成功提交，我们的客服会与你联系！');
	} else {
		return drupal_set_message($result['reason'], 'error');
	}

}

function cowpro_shop_userpoints_list_transactions_alter(&$output) {
	ctools_include ( 'modal' );
	ctools_include ( 'ajax' );
	ctools_modal_add_js ();

	$account = $output['#account'];
	$output['list']['summary_table'] = array(
			'#theme' => 'table',
			'#header' => array(
					array(
							'data' => '积分与奖金',
							'colspan' => 3,
					),
			),
			'#rows' => array(
					array(
							'data' => array('积分', userpoints_get_current_points($account->uid), ''),
							'class' => array('userpoints-myuserpoints-total-approved'),
					),
					array(
							'data' => array('奖金', userpoints_get_current_points($account->uid, _cowpro_shop_get_user_points_money_tid()), ctools_modal_text_button ( '兑现奖金', 'shop/redemption', '兑现奖金' )),
							'class' => array('userpoints-myuserpoints-total-approved'),
					),
			),
			'#weight' => 10,
			'#attributes' => array('class' => array('userpoints-myuserpoints-total')),
	);
}

define('COWPRO_USERPOINTS_MONEY', '奖金');
function _cowpro_shop_get_user_points_money_tid()
{
	$term = current(taxonomy_get_term_by_name(COWPRO_USERPOINTS_MONEY));
	return $term->tid;
}

function cowpro_shop_redemption() {
	form_load_include($form_state, 'inc', 'cowpro_shop', 'cowpro_shop_redemption');

	ctools_include('modal');
	ctools_include('ajax');
	$form_state = array(
			'title' => '兑现奖金',
			'ajax' => TRUE,
	);
	$commands = ctools_modal_form_wrapper('cowpro_shop_redemption_form', $form_state);

	//以AJAX方式驱动modal窗口的显示的时候，暂时没有找到更好的定义窗口维度的方法，所以暂时用js的方式来实现
	$js = <<<js
	<script type="text/javascript">
	var width = 800;
	var height = 700;
	var contentRight = 25;
    var contentBottom = 45;
	jQuery('div.ctools-modal-content').css({
		'width': width + 'px',
		'height': height + 'px'
	});
    jQuery('div.ctools-modal-content .modal-content').css({
        'width': (width - contentRight) + 'px',
        'height': (height - contentBottom) + 'px'
    });
	var styleProps = jQuery('#modalContent').css('top');
	modalContentResize();
	jQuery('#modalContent').css('top', styleProps);
	</script>
js;

	$commands[0]['output'] .= $js;

	print ajax_render($commands);
	exit;

}