<?php
const MMM_OP_BIND_ACCOUNT = '关联乾多多账户';
const MMM_OP_AUTHORIZE = '授权对乾多多帐户操作';

const PLATFORM_ACCOUNT_ON_MONEYMOREMORE = 'platform_account_on_moneymoremore';//测试环境'p1472'
const PUBLIC_KEY_ON_MONEYMOREMORE = 'public_key_on_moneymoremore';
const PRIVATE_KEY_ON_MONEYMOREMORE = 'private_key_on_moneymoremore';

const MMM_URL_RESPONSE = '/cowpro/moneymoremore/response/';
const MMM_URL_NOTIRY = '/cowpro/moneymoremore/callback/';

 //正式环境
 const MMM_URL_REGISTER = 'https://register.moneymoremore.com/loan/toloanregisterbind.action';
 const MMM_URL_TRANSFER = 'https://transfer.moneymoremore.com/loan/loan.action';
 const MMM_URL_QUERY_BALANCE = 'https://query.moneymoremore.com/loan/balancequery.action';
 const MMM_URL_RECHARGE = 'https://recharge.moneymoremore.com/loan/toloanrecharge.action';
 const MMM_URL_WITHDRAWALS = 'https://withdrawals.moneymoremore.com/loan/toloanwithdraws.action';
 const MMM_URL_ORDER_QUERY = 'https://query.moneymoremore.com/loan/loanorderquery.action';//对账接口
 const MMM_URL_AUTHORIZE = 'https://auth.moneymoremore.com/loan/toloanauthorize.action';
 const MMM_URL_AUDIT = 'https://audit.moneymoremore.com/loan/toloantransferaudit.action';

 //测试环境
 /*
 const MMM_URL_REGISTER = 'http://test.moneymoremore.com:88/main/loan/toloanregisterbind.action';
 const MMM_URL_TRANSFER = 'http://test.moneymoremore.com:88/main/loan/loan.action';
 const MMM_URL_QUERY_BALANCE = 'http://test.moneymoremore.com:88/main/loan/balancequery.action';
 const MMM_URL_RECHARGE = 'http://test.moneymoremore.com:88/main/loan/toloanrecharge.action';
 const MMM_URL_WITHDRAWALS = 'http://test.moneymoremore.com:88/main/loan/toloanwithdraws.action';
 const MMM_URL_ORDER_QUERY = 'http://test.moneymoremore.com:88/main/loan/loanorderquery.action';//对账接口
 const MMM_URL_AUTHORIZE = 'http://test.moneymoremore.com:88/main/loan/toloanauthorize.action';
 const MMM_URL_AUDIT = 'http://test.moneymoremore.com:88/main/loan/toloantransferaudit.action';
*/
