<?php
const MOBILE_CERTIFICATION_SMS_TEMPLATE = '您在“[site:name]”网站的手机验证码是[code]';

/**
 * Implementation of hook_menu()
 */
function mobile_certification_menu() {
	$items ['cowpro/mobile-verify-send-code'] = array (
			'title' => 'Mobile Certification Send Code',
			'page callback' => 'mobile_certification_send_code',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);

	$items ['admin/cowpro/config_mobile_certification'] = array (
			'title' => '手机认证短信模板',
			'description' => '设置手机认证短信的内容',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					'mobile_certification_settings_form',
			),
			'access arguments' => array (
					'configure p2p',
			),
			'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

/**
 * Implements hook_views_api().
 */
function mobile_certification_views_api() {
	return array (
			'api' => 3,
			'path' => drupal_get_path ( 'module', 'mobile_certification' ) . '/includes/views',
	);
}
function mobile_certification_cowpro_customer_profile_mobile_create($values) {
	$values += array (
			'mobile_number' => '',
	) // 手机号码
;
	return $values;
}
function mobile_certification_cowpro_customer_profile_mobile_save($profile) {
	$data = array ();
	$data ['mobile_number'] = $profile->mobile_number;
	$profile->data = $data;
	$profile->verified = TRUE;
	return $profile;
}
function mobile_certification_cowpro_customer_profile_mobile_load($profile) {
	$profile->mobile_number = $profile->data ['mobile_number'];
	return $profile;
}
function mobile_certification_cowpro_customer_profile_mobile_form($form, &$form_state, $profile) {
	global $base_url;
	drupal_add_js(array('basePath' => $base_url), 'setting');
	drupal_add_js ( drupal_get_path ( 'module', 'mobile_certification' ) . '/mobile_certification.js' );
	$form ['mobile_number'] = array (
			'#type' => 'textfield',
			'#title' => '手机号码',
			'#description' => '',
			'#default_value' => $profile->mobile_number,
			'#maxlength' => 20,
			'#required' => TRUE,
			'#attributes' => array (
					'class' => array (
							'mobile_number',
					)
			),
			'#weight' => - 10,
	);

	$form ['verify_code'] = array (
			'#type' => 'textfield',
			'#title' => '验证码',
			'#default_value' => '',
			'#maxlength' => 20,
			'#required' => FALSE,//在通过 registration_wizard 模块显示这个 form 的时候，用户有可能只是在向导翻页的时候路过
			'#weight' => - 5,
	);

	$form ['send_verify'] = array (
			'#id' => 'send_verify',
			'#type' => 'button',
			'#value' => '发送验证码',
			'#attributes' => array (
					'class' => array (
							'send-verify-code',
					)
			),
			'#weight' => 10,
	);

	$form ['mobile_verify_help'] = array (
			'#markup' => '<div id=mobile_verify_help><p></p></div>',
			'#weight' => 5,
	);

	return $form;
}
function mobile_certification_cowpro_customer_profile_mobile_form_validate($form, &$form_state, $profile) {
	$validate_result = TRUE;
	if (!isset($_SESSION ['mobile_verification_mobile_number'])) {
		$validate_result = FALSE;
	}
	if (!isset($_SESSION ['mobile_verification_code'])) {
		$validate_result = FALSE;
	}
	if ($validate_result && ($_SESSION ['mobile_verification_mobile_number'] != trim ( $form_state ['values'] ['mobile_number'] ))) {
		$validate_result = FALSE;
	}
	if ($validate_result && ($_SESSION ['mobile_verification_code'] != trim ( $form_state ['values'] ['verify_code'] ))) {
			$validate_result = FALSE;
	}
	if (!$validate_result) {
		form_set_error ( '验证码', '您输入的验证码不正确.' );
	}
}
function mobile_certification_cowpro_customer_profile_mobile_form_submit($form, &$form_state, &$profile) {
	$profile->mobile_number = $form_state ['values'] ['mobile_number'];
}
function mobile_certification_cowpro_customer_profile_mobile_extra_fields() {
	$result = array (
			'form' => array (
					'name' => array (
							'label' => '手机',
							'description' => '手机号码',
							'weight' => - 9,
					)
			),
			'display' => array (
					'name' => array (
							'label' => '手机',
							'description' => '手机号码',
							'weight' => - 9,
					)
			)
	);

	return $result;
}

/**
 * Implements hook_cowpro_customer_profile_type_info().
 */
function mobile_certification_cowpro_customer_profile_type_info() {
	$profile_types = array ();

	$profile_types ['mobile'] = array (
			'type' => 'mobile',
			'name' => '手机认证',
			'description' => '通过手机短信验证码的形式，对用户提供的手机号进行认证。',
			'help' => '',
			'weight' => 100,
	);

	return $profile_types;
}
function mobile_certification_send_code() {
	$mobile_number = $_GET ['mobile_number'];
	if ($mobile_number) {
		// 4-digit random code
		$code = rand ( pow ( 10, 3 ), pow ( 10, 4 ) - 1 );

		// save code in session
		$_SESSION ['mobile_verification_code'] = $code;
		$_SESSION ['mobile_verification_mobile_number'] = $mobile_number;

		// watchdog('debug', "$key code: " . $code);

		$text = variable_get ( 'mobile_verify_sms_template', MOBILE_CERTIFICATION_SMS_TEMPLATE );
		$site_name = variable_get ( 'site_name' );
		$text = str_replace ( '[site:name]', $site_name, $text );
		$text = str_replace ( '[code]', $code, $text );
		$successed = cowpro_message_send ( $mobile_number, $text );

		if ($successed) {
			$response = array (
					'status' => 200,
			);
		} else {
			$response = array (
					'status' => 500,
					'message' => '短消息发送失败，请联系网站管理员.',
			);
		}
	} else {
		$response = array (
				'status' => 500,
				'message' => 'Server error.',
		);
	}
	drupal_json_output ( $response );
}
function mobile_certification_settings_form($form, &$form_state) {
	$form = array ();
	$form ['mobile_verify_sms_template'] = array (
			'#title' => '手机验证短信模板',
			'#type' => 'textarea',
			'#default_value' => variable_get ( 'mobile_verify_sms_template', MOBILE_CERTIFICATION_SMS_TEMPLATE ),
	);
	$form ['mobile_verify_sms_template_help'] = array (
			'#markup' => '模板中可用的变量：<br/><b>[site_name]</b> : 网站名称<br/><b>[code]</b> : 验证码',
	);
	$form ['actions'] = array (
			'#type' => 'actions',
	);
	$form ['actions'] ['submit'] = array (
			'#type' => 'submit',
			'#value' => t ( "Save" ),
			'#weight' => 10,
	);
	return system_settings_form ( $form );
}
