<?php
define ( "TARE_MAX", "10000" );
function cowpro_draw_menu() {
	$items = array ();
	$items ['cowpro/draw'] = array (
			'title' => '红包抽奖',
			'description' => '红包抽奖',
			'page callback' => 'cowpro_draw_show',
			'access callback' => 'cowpro_draw_verified'
	);
	return $items;
}

/**
 * Implements hook_theme().
 */
function cowpro_draw_theme() {
	return array (
			'cowpro_draw_see' => array (
					'variables' => array (
							'items' => NULL,
					),
					'template' => 'cowpro-draw-see',
			),
	);
}
function cowpro_draw_show() {
	global $user;
	$items ['success'] = $_GET ['success'];
	$items ['issuing_id'] = intval ( $_GET ['nid'] );
	$items ['journal_id'] = intval ( $_GET ['journal_id'] );
	$journal_result = db_query ( "SELECT * FROM {cowpro_fund_journal} WHERE uid=" . $user->uid . " AND issuing_id=" . $items ['issuing_id'] . " AND journal_id=" . $items ['journal_id'] . " AND type='BID'" )->fetchAll ();
	$amount = $journal_result [0]->amount;
	$node = node_load ( $items ['issuing_id'] );
	$issuing = $node->field_issuing [LANGUAGE_NONE] [0];
	$loan_term = $issuing ['loan_term'];
	$rate = ($amount / 12) * ($loan_term / 30);

	if ($rate < TARE_MAX) {
		$html = theme ( 'cowpro_draw_see', array (
				'items' => $items,
				'winning' => null,
				'is_permissions' => 0,
		) );
		return $html;
	}

	$prize_arr = array (
			'0' => array (
					'id' => 1,
					'prize' => '20积分',
					'v' => 5,
					"type" => "points",
					"amount" => "20",
			),
			'1' => array (
					'id' => 2,
					'prize' => '50积分',
					'v' => 10,
					"type" => "points",
					"amount" => "50",
			),
			'2' => array (
					'id' => 10,
					'prize' => '100积分',
					'v' => 10,
					"type" => "points",
					"amount" => "100",
			),
			'3' => array (
					'id' => 4,
					'prize' => '20元代金券',
					'v' => 40,
					"type" => "voucher",
					"amount" => "20",
			),
			'4' => array (
					'id' => 5,
					'prize' => '50元代金券',
					'v' => 20,
					"type" => "voucher",
					"amount" => "50",
			),
			'5' => array (
					'id' => 6,
					'prize' => '100元代金券',
					'v' => 10,
					"type" => "voucher",
					"amount" => "100",
			),
			'6' => array (
					'id' => 7,
					'prize' => '谢谢参与！',
					'v' => 5,
					"type" => "",
					"amount" => "0",
			)
	);
	foreach ( $prize_arr as $key => $val ) {
		$arr [$val ['id']] = $val ['v'];
	}
	$rid = _cowpro_draw_get_rand ( $arr ); // 根据概率获取奖项id

	$res ['yes'] = $prize_arr [$rid - 1]; // 中奖项
	unset ( $prize_arr [$rid - 1] ); // 将中奖项从数组中剔除，剩下未中奖项
	shuffle ( $prize_arr ); // 打乱数组顺序
	for($i = 0; $i < count ( $prize_arr ); $i ++) {
		$pr [] = $prize_arr [$i];
	}
	$res ['no'] = $pr;

	$insert_data ['uid'] = $user->uid;
	$insert_data ['issuing_id'] = $items ['issuing_id'];
	$insert_data ['journal_id'] = $items ['journal_id'];
	$insert_data ['type'] = $res ['yes'] ['type'] == "voucher" ? 1 : 0;
	$insert_data ['amount'] = $res ['yes'] ['amount'];
	$insert_data ['created'] = time ();
	$insert_id = db_insert ( 'cowpro_draw' )->fields ( $insert_data )->execute ();
	$expirydate = time () + (10 * 3600 * 24);
	if ($insert_id) {
		if ($res ['yes'] ['type'] == "voucher") {
			$term = current ( taxonomy_get_term_by_name ( '代金券' ) );
			$params = array (
					'uid' => $user->uid,
					'points' => $res ['yes'] ['amount'],
					'description' => '投资后红包抽奖:' . $node->title,
					'display' => FALSE,
					'entity_type' => 'node',
					'entity_id' => $items ['issuing_id'],
					'tid' => $term->tid,
					'reference' => "draw",
					'expirydate' => $expirydate,
			);
		} else {
			$params = array (
					'uid' => $user->uid,
					'points' => $res ['yes'] ['amount'],
					'description' => '投资后红包抽奖:' . $node->title,
					'display' => FALSE,
					'entity_type' => 'node',
					'entity_id' => $items ['issuing_id'],
					'tid' => 0,
					'reference' => "draw",
					'expirydate' => $expirydate,
			);
		}
		userpoints_userpointsapi ( $params );
		$html = theme ( 'cowpro_draw_see', array (
				'items' => $items,
				'winning' => $res ['yes'],
				'is_permissions' => 1
		) );
		return $html;
	}
}
function cowpro_draw_verified() {
	global $user;
	$success = @$_GET ['success'];
	$issuing_id = @$_GET ['nid'];
	$journal_id = @$_GET ['journal_id'];

	if ($success && is_numeric ( $issuing_id ) && is_numeric ( $journal_id )) {
		$journal_result = db_query ( "SELECT * FROM {cowpro_fund_journal} WHERE uid=" . $user->uid . " AND issuing_id=" . $issuing_id . " AND journal_id=" . $journal_id . " AND type='BID'" )->fetchAll ();
		$result = db_query ( "SELECT * FROM {cowpro_draw} WHERE uid=" . $user->uid . " AND issuing_id=" . $issuing_id . " AND journal_id=" . $journal_id . "" )->fetchAll ();
		if (! $result && $journal_result) {
			return true;
		} else {
			return false;
		}
	} else {
		return false;
	}
}
function _cowpro_draw_get_rand($proArr) {
	$result = '';
	// 概率数组的总概率精度
	$proSum = array_sum ( $proArr );
	// 概率数组循环
	foreach ( $proArr as $key => $proCur ) {
		$randNum = mt_rand ( 1, $proSum );
		if ($randNum <= $proCur) {
			$result = $key;
			break;
		} else {
			$proSum -= $proCur;
		}
	}
	unset ( $proArr );
	return $result;
}
