<?php
define ( "TARE_MAX", "10000" );
function cowpro_draw_menu() {
	$items = array ();
	$items ['cowpro/draw'] = array (
			'title' => '红包抽奖',
			'description' => '红包抽奖',
			'page callback' => 'cowpro_draw_show',
			'access callback' => 'cowpro_draw_verified'
	);
	return $items;
}

/**
 * Implements hook_theme().
 */
function cowpro_draw_theme() {
	return array (
			'cowpro_draw_see' => array (
					'variables' => array (
							'items' => NULL,
					),
					'template' => 'cowpro-draw-see',
			),
	);
}
function cowpro_draw_show() {
	global $user;
	$items ['success'] = $_GET ['success'];
	$items ['issuing_id'] = intval ( $_GET ['nid'] );
	$items ['journal_id'] = intval ( $_GET ['journal_id'] );
	$journal_result = db_query ( "SELECT * FROM {cowpro_fund_journal} WHERE uid=" . $user->uid . " AND issuing_id=" . $items ['issuing_id'] . " AND journal_id=" . $items ['journal_id'] . " AND type='BID'" )->fetchAll ();
	$amount = $journal_result [0]->amount;
	$node = node_load ( $items ['issuing_id'] );
	$issuing = $node->field_issuing [LANGUAGE_NONE] [0];
	$loan_term = $issuing ['loan_term'];
	$rate = ($amount / 12) * ($loan_term / 30);

	if ($rate < TARE_MAX) {
		$html = theme ( 'cowpro_draw_see', array (
				'items' => $items,
				'winning' => null,
				'is_permissions' => 0,
		) );
		return $html;
	}

	$prize_arr = array (
			'0' => array (
					'id' => 1,
					'prize' => '20积分',
					'v' => 5,
					"type" => "points",
					"amount" => "20",
			),
			'1' => array (
					'id' => 2,
					'prize' => '50积分',
					'v' => 10,
					"type" => "points",
					"amount" => "50",
			),
			'2' => array (
					'id' => 10,
					'prize' => '100积分',
					'v' => 10,
					"type" => "points",
					"amount" => "100",
			),
			'3' => array (
					'id' => 4,
					'prize' => '20元代金券',
					'v' => 40,
					"type" => "voucher",
					"amount" => "20",
			),
			'4' => array (
					'id' => 5,
					'prize' => '50元代金券',
					'v' => 20,
					"type" => "voucher",
					"amount" => "50",
			),
			'5' => array (
					'id' => 6,
					'prize' => '100元代金券',
					'v' => 10,
					"type" => "voucher",
					"amount" => "100",
			),
			'6' => array (
					'id' => 7,
					'prize' => '谢谢参与！',
					'v' => 5,
					"type" => "",
					"amount" => "0",
			)
	);
	foreach ( $prize_arr as $key => $val ) {
		$arr [$val ['id']] = $val ['v'];
	}
	$rid = _get_rand ( $arr ); // 根据概率获取奖项id

	$res ['yes'] = $prize_arr [$rid - 1]; // 中奖项
	unset ( $prize_arr [$rid - 1] ); // 将中奖项从数组中剔除，剩下未中奖项
	shuffle ( $prize_arr ); // 打乱数组顺序
	for($i = 0; $i < count ( $prize_arr ); $i ++) {
		$pr [] = $prize_arr [$i];
	}
	$res ['no'] = $pr;

	$insert_data ['uid'] = $user->uid;
	$insert_data ['issuing_id'] = $items ['issuing_id'];
	$insert_data ['journal_id'] = $items ['journal_id'];
	$insert_data ['type'] = $res ['yes'] ['type'] == "voucher" ? 1 : 0;
	$insert_data ['amount'] = $res ['yes'] ['amount'];
	$insert_data ['created'] = time ();
	$insert_id = db_insert ( 'cowpro_draw' )->fields ( $insert_data )->execute ();
	$expirydate = time () + (10 * 3600 * 24);
	if ($insert_id) {
		if ($res ['yes'] ['type'] == "voucher") {
			$term = current ( taxonomy_get_term_by_name ( '代金券' ) );
			$params = array (
					'uid' => $user->uid,
					'points' => $res ['yes'] ['amount'],
					'description' => '投资后红包抽奖:' . $node->title,
					'display' => FALSE,
					'entity_type' => 'node',
					'entity_id' => $items ['issuing_id'],
					'tid' => $term->tid,
					'reference' => "draw",
					'expirydate' => $expirydate,
			);
		} else {
			$params = array (
					'uid' => $user->uid,
					'points' => $res ['yes'] ['amount'],
					'description' => '投资后红包抽奖:' . $node->title,
					'display' => FALSE,
					'entity_type' => 'node',
					'entity_id' => $items ['issuing_id'],
					'tid' => 0,
					'reference' => "draw",
					'expirydate' => $expirydate,
			);
		}
		userpoints_userpointsapi ( $params );
		$html = theme ( 'cowpro_draw_see', array (
				'items' => $items,
				'winning' => $res ['yes'],
				'is_permissions' => 1
		) );
		return $html;
	}
}
function cowpro_draw_verified() {
	global $user;
	$success = @$_GET ['success'];
	$issuing_id = @$_GET ['nid'];
	$journal_id = @$_GET ['journal_id'];

	if ($success && is_numeric ( $issuing_id ) && is_numeric ( $journal_id )) {
		$journal_result = db_query ( "SELECT * FROM {cowpro_fund_journal} WHERE uid=" . $user->uid . " AND issuing_id=" . $issuing_id . " AND journal_id=" . $journal_id . " AND type='BID'" )->fetchAll ();
		$result = db_query ( "SELECT * FROM {cowpro_draw} WHERE uid=" . $user->uid . " AND issuing_id=" . $issuing_id . " AND journal_id=" . $journal_id . "" )->fetchAll ();
		if (! $result && $journal_result) {
			return true;
		} else {
			return false;
		}
	} else {
		return false;
	}
}
function _get_rand($proArr) {
	$result = '';
	// 概率数组的总概率精度
	$proSum = array_sum ( $proArr );
	// 概率数组循环
	foreach ( $proArr as $key => $proCur ) {
		$randNum = mt_rand ( 1, $proSum );
		if ($randNum <= $proCur) {
			$result = $key;
			break;
		} else {
			$proSum -= $proCur;
		}
	}
	unset ( $proArr );
	return $result;
}

// 获取代金券显示在投资页面
function cowpro_draw_cowpro_issuing_bid_form($form, $form_state) {
	global $user;
	// 获取表里该用户未使用并且没过期的代金券
	$term = current ( taxonomy_get_term_by_name ( '代金券' ) );
	$result = db_query ( "SELECT txn_id,points FROM {userpoints_txn} WHERE uid=" . $user->uid . " and tid=" . $term->tid . " and expired=0" );
	if ($result !== FALSE) {
		// 将代金券输出为数组显示在投资页面,默认选项是“不使用代金券”,值为0
		$item_points = array ();
		$item_points['0_0'] = '不使用代金券';
		foreach ( $result as $data ) {
			$item_points [$data->txn_id . "_" . $data->points] = $data->points . "元代金券";
		}
		$items = array ();
		$items ['voucher'] = array (
				'#type' => 'select',
				'#title' => '代金券选项',
				'#options' => $item_points,
				'#description' => '',
		);
		return $items;
	}
}

// 代金券使用验证
function cowpro_draw_cowpro_issuing_bid_form_validate($form, $form_state) {
	if ($form_state ['values'] ['voucher'] != '0_0') {
		$right_voucher = end ( explode ( '_', $form_state ['values'] ['voucher'] ) );
		if ($form_state ['values'] ['amount'] <= 100) {
			form_set_error ( 'bid', '投资金额大于10000才能使用代金券' );
		}
		if (($form_state ['values'] ['amount'] >= 100) && ($form_state ['values'] ['amount'] <= 300)) {
			if ($right_voucher > 20) {
				form_set_error ( 'bid', '投资金额大于10000且小于30000只能使用20元代金券' );
			}
		}
		if (($form_state ['values'] ['amount'] >= 300) && ($form_state ['values'] ['amount'] <= 500)) {
			if ($right_voucher > 50) {
				form_set_error ( 'bid', '投资金额大于30000且小于50000只能使用50元及小于50元的代金券' );
			}
		}
	}
}

// 投资提交
function cowpro_draw_cowpro_issuing_bid_form_submit($form, $form_state) {
	if ($form_state ['values'] ['voucher'] != '0_0') {
		// 判断如果使用代金券就站内转账
		global $user;
		$txn_id = reset ( explode ( '_', $form_state ['values'] ['voucher'] ) ); // 获取代金券ID
		$right_voucher = end ( explode ( '_', $form_state ['values'] ['voucher'] ) ); // 获取代金券金额

		$uid_from = user_load_by_name ( variable_get ( 'fund_imprest_account', '' ) )->uid; // 转出账户ID
		$uid_to = $user->uid; // 转入账户ID
		$amount = $right_voucher; // 转入金额
		$comment = '使用红包';

		$result = custodian_cowpro_fund_internal_trans ( $uid_from, $uid_to, $amount, $comment);

		if ($result ['success']) {
			$term = current ( taxonomy_get_term_by_name ( '代金券' ) );
			$desc = "投资使用代金券：" . $amount . "元代金券";
			$issuing_id = $form_state ['nid'];
			$params = array (
					'txn_id' => $txn_id,
					'uid' => $user->uid,
					'points' => 0 - $amount,
					'description' => $desc,
					'display' => false,
					'tid' => $term->tid,
					'reference' => "draw:node:$issuing_id",
					'expired' => true,
			);
			$result = userpoints_userpointsapi ( $params );
			return true;
		} else {
			$message = '代金券转账失败';
			drupal_set_message ( $message, 'error' );
			return false;
		}
	} else {
		return true;
	}
}
function cowpro_draw_cowpro_issuing_bid_finished($success, $nid, $journal_id) {
	ctools_include ( 'modal' );
	ctools_include ( 'ajax' );
	$commands = array ();
	$url = $GLOBALS['base_url'] . '/cowpro/draw';
	$delay = 0;
	$options = array ();
	$options ['query'] = array (
			'success' => $success,
			'nid' => $nid,
			'journal_id' => $journal_id
	);
	$commands [] = ctools_ajax_command_redirect ( $url, $delay, $options );
	print ajax_render ( $commands );
	drupal_exit ();
}
