<?php

/**
 * Implementation of hook_menu()
 */
function cowpro_rewards_menu() {
  $items['cowpro/rewards/employee_registration'] = array(
    'title' => '员工登记',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'cowpro_rewards_employee_registration_form'
    ),
    'access arguments' => array(
      'access user profiles'
    ),
    'file' => 'includes/rewards.employee_registration.inc',
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

/*
 * 实现 hook_cowpro_promotion_info
 */
function cowpro_rewards_cowpro_promotion_info() {
  $items = array();
  //注意：$items的 key 是全系统唯一的，模块内以及模块之间都不要冲突
  $items['cowpro_rewards_make_loans_to_finished'] = array(
    'title' => '满标放款以后，发放积分',
    'description' => '满标放款以后，年化投资额的五十分之一，做为投资者的奖励积分',
    'duration_begin' => null,//活动开始时间(格式为'Y-m-d H:i:s')，如果未设置，则即时开始
    'duration_end' => null,//活动开始时间(格式为'Y-m-d H:i:s')，如果未设置，则活动一直有效
    'event' => 'cowpro_fund_make_loans_to_finished',//由此事件触发
    'action' => 'cowpro_reward_make_loans_to_finished',//执行这个动作
  );
  $items['cowpro_rewards_repayment_finished'] = array(
    'title' => '到期还款以后，发放奖金',
    'description' => '到期还款以后，年化投资额的千分之三，以现金的形式分期奖励投资人的推荐人；年化投资额的千分之二，以现金的形式分期奖励投资人的推荐人的推荐人',
    'duration_begin' => null,//活动开始时间(格式为'Y-m-d H:i:s')，如果未设置，则即时开始
    'duration_end' => null,//活动开始时间(格式为'Y-m-d H:i:s')，如果未设置，则活动一直有效
    'event' => 'cowpro_fund_repayment_finished',//由此事件触发
    'action' => 'cowpro_reward_repayment_finished',//执行这个动作
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function cowpro_rewards_theme() {
	return array (
			'cowpro_rewards_issuing_list' => array (
                            'variables' => array (
                                            'journal_list' => NULL,
                            ),
                            'template' => 'cowpro-rewards-issuing-list',
			),
	);
}

/**
 * Implements hook_node_view().
 */
function cowpro_rewards_node_view($node, $view_mode){
    if ($node->type != 'cowpro_issuing') {
            return;
    }
    global $user;
     $role = user_role_load_by_name ( 'administrator' );
     if (user_has_role ( $role->rid, $user )) {
        if ($view_mode == 'full') {
            drupal_add_css(drupal_get_path('module', 'cowpro_issuing') . "/theme/cowpro_issuing.theme.css");
            $node->content['my_field']['stuff'][5] = array(
                                    '#type' => 'fieldset',
                                    '#title' => '奖励记录',
                                    '#collapsible' => TRUE,
                                    '#collapsed' => TRUE,
                    );

            $node->content['my_field']['stuff'][5]['issuing_list'] = array (
                '#markup' => theme ( 'cowpro_rewards_issuing_list', array (
                            'journal_list' => cowpro_rewards_issuing_list ( $node->nid ),
                ) ) ,
            );
        }
    }
}

//userpoints_txn 获取对应标的奖励列表
function cowpro_rewards_issuing_list($nid){
    $query = db_select('userpoints_txn', 'p');
    $query->addField('p', 'uid');
    $query->addField('p', 'points');
    $query->addField('p', 'time_stamp');
    $query->addField('p', 'tid');
    $query->addField('p', 'description');
    $query->condition('p.entity_type', 'node', '=');
    $query->condition('p.entity_id', $nid, '=');
    $result = $query->execute()->fetchAll();
    $type = array( 0 => "积分",17 => "奖金");
    foreach( $result as $key=>$value ){
       $real_name = cowpro_customer_profile_load_one_row_with_conditions ( $value->uid, 'real_name' );
       if( $real_name ) {
          $result[$key]->real_name = $real_name->name; 
       }else{
          $result[$key]->real_name = "";
       }
       $user = user_load($value->uid);
       $result[$key]->nick_name = $user->name;
       $result[$key]->created = date('Y/m/d - H:i', $value->time_stamp);
       $result[$key]->type = $type[$value->tid];
    }
    return $result;
}
