<?php
define("SIX_RATE", "10.20");
define("TWELVE_RATE", "10.80");
/**
 * Implementation of hook_menu()
 */
function cowpro_rewards_menu() {
	$items ['cowpro/rewards/check_in'] = array (
			'title' => '签到',
			'description' => '',
			'page callback' => 'cowpro_rewards_check_in',
			'page arguments' => array (),
			'access callback' => 'user_is_logged_in',
			'type' => MENU_NORMAL_ITEM,
	);
	$items ['cowpro/rewards/employee_registration'] = array (
			'title' => '员工登记',
			'description' => '',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					'cowpro_rewards_employee_registration_form'
			),
			'access arguments' => array (
					'access user profiles',
			),
			'file' => 'includes/rewards.employee_registration.inc',
			'type' => MENU_NORMAL_ITEM,
	);
	$items ['cowpro/rewards/february'] = array (
			'title' => '二月推荐奖励列表',
			'description' => '',
			'page callback' => 'cowpro_rewards_february',
			'access arguments' => array (
					'configure p2p',
			),
			'type' => MENU_NORMAL_ITEM,
	);
        $items ['cowpro/rewards/issuing_large'] = array (
                'title' => '大额奖励明细',
                'description' => '',
                'page callback' => 'cowpro_rewards_insert_issuing_large_data',
                'access arguments' => array (
                                'configure p2p'
                ),
                'type' => MENU_NORMAL_ITEM
	);
         $items ['cowpro/rewards/issuing_large_op'] = array (
                'title' => '大额奖励转账',
                'description' => '',
                'page callback' => 'drupal_get_form',
                'page arguments' => array (
					'cowpro_rewards_issuing_large_go_form'
			),
                'access arguments' => array (
                                'configure p2p'
                ),
                'file' => 'includes/rewards.issuing_large.inc',
                'type' => MENU_NORMAL_ITEM
	);
        $items ['cowpro/rewards/taiz_op'] = array (
                'title' => '标的台账余额',
                'description' => '',
                'page callback' => 'drupal_get_form',
                'page arguments' => array (
					'cowpro_rewards_taiz_op_go_form'
			),
                'access arguments' => array (
                                'configure p2p'
                ),
                'file' => 'includes/rewards.taiz_op.inc',
                'type' => MENU_NORMAL_ITEM
	);
	return $items;
}

// 2018 2月推荐奖励
function cowpro_rewards_february() {
	$result = db_query ( "SELECT requester_id,requestee_id FROM {user_relationships} WHERE rtid=1" )->fetchAll ( PDO::FETCH_ASSOC );
	$list = array ();
	$bount1 = array ();
	$bount2 = array ();
	foreach ( $result as $value ) {
		$list [$value ['requestee_id']] [] = $value ['requester_id'];
	}

	foreach ( $list as $key => $value ) {

		$implode_string = implode ( ",", $list [$key] );
		$start_time = strtotime ( "2018-02-01 00:00:00" );
		$end_time = strtotime ( "2018-02-28 23:59:59" );
		$result_bid_count = db_query ( "SELECT distinct uid FROM {cowpro_fund_journal} WHERE type='BID' AND status=1 AND uid in(" . $implode_string . ") AND amount >= 10000 AND created>='" . $start_time . "' AND created<='" . $end_time . "'" )->fetchAll ( PDO::FETCH_ASSOC );

		$bount1 [$key] ['count'] = $result_bid_count [0] ['count'];
		$bount2_uid = db_query ( "SELECT requestee_id FROM {user_relationships} WHERE rtid=1 AND requester_id=" . $key )->fetchAll ( PDO::FETCH_ASSOC );
		if (! empty ( $bount2_uid )) {
			$bount2 [$bount2_uid [0] ['requestee_id']] ['count'] = $result_bid_count [0] ['count'];
		}
	}

	foreach ( $bount1 as $key => $value ) {
		$profile_real_name = cowpro_customer_profile_load_one_row_with_conditions ( $key, 'real_name' );
		if ($profile_real_name)
			$bount1 [$key] ['name'] = $profile_real_name->name;

		if ($value ['count'] - 2 > 0) {
			$bount1 [$key] ['amount'] = ($value ['count'] - 2) * 20;
			$bount1 [$key] ['voucher'] = ($value ['count'] - 2) * 30;
		} else {
			unset ( $bount1 [$key] );
		}
	}

	foreach ( $bount2 as $key => $value ) {

		if ($value ['count'] > 0) {
			$profile_real_name = cowpro_customer_profile_load_one_row_with_conditions ( $key, 'real_name' );
			if ($profile_real_name)
				$name = $profile_real_name->name;
			$bount2 [$key] ['amount'] = $value ['count'] * 10;
			$bount2 [$key] ['name'] = $name;
		} else {
			unset ( $bount2 [$key] );
		}
	}

	$html = theme ( 'cowpro_rewards_february', array (
			'bount1' => $bount1,
			'bount2' => $bount2,
	) );
	return $html;
}

/**
 * Implements hook_theme().
 */
function cowpro_rewards_theme() {
	return array (
			'cowpro_rewards_february' => array (
					'variables' => array (
							'bount1' => NULL,
							'bount2' => NULL
					),
					'template' => 'cowpro-rewards-february'
			),
	);
}
function cowpro_rewards_check_in() {
	$uid = $GLOBALS ['user']->uid;
	if (cowpro_rewards_have_checked_in ()) {
		drupal_set_message ( '亲，今天已经签过到啦，请明来再来！', 'warning' );
		drupal_goto ();
		return;
	}

	db_merge ( 'cowpro_rewards_checkin' )->key ( array (
			'uid' => $uid
	) )->fields ( array (
			'uid' => $uid,
			'last_checkin' => time ()
	) )->execute ();

	$points = 1;
	$params = array (
			'uid' => $uid,
			'points' => $points,
			'description' => '签到奖励',
			'display' => FALSE,
			'tid' => 0
	) // 积分
;
	userpoints_userpointsapi ( $params );
        $block = block_load("cowpro_fund","cowpro_fund_user");
        $cache_id = _block_get_cache_id($block);

        cache_clear_all($cache_id,"cache_block");
	drupal_set_message ( '签到奖励积分1个！' );
	drupal_goto ();
	// return '欢迎签到';
}
function cowpro_rewards_have_checked_in() {
	$uid = $GLOBALS ['user']->uid;
	$start_time = mktime ( 0, 0, 0, date ( "n" ), date ( "j" ), date ( "Y" ) ); // 今天零时
	$query = db_select ( 'cowpro_rewards_checkin', 'checkin' )->fields ( 'checkin', array (
			'uid',
			'last_checkin'
	) )->condition ( 'uid', $uid )->condition ( 'last_checkin', $start_time, '>' );

	if ($query->execute ()->fetchObject ()) {
		return TRUE;
	} else {
		return FALSE;
	}
}

/*
 仅用于测试，当用户登录的时候，触发cowpro_fund_bid_finished event
 */
/*
function cowpro_rewards_user_login(&$edit, $account) {
	$uid = $GLOBALS ['user']->uid;
	if ($uid != 70041) {//只有用户 bigbug 登录的时候，才触发后面的逻辑
		return;
	}

	$issuing_id = 2500;
	$period = 1;
	$node = node_load($issuing_id);

	$repayment_schedules = array();
	$conditions = array (
			'issuing_id' => $issuing_id,
			'period' => $period,
			//'status' => 'WAITING_FOR',
	);
	$reset = FALSE;
	$schedules = entity_load ( 'cowpro_repayment_schedule', FALSE, $conditions, $reset );
	foreach ($schedules as $schedule) {
		if ($schedule->receiver_uid != -1) {
			$repayment_schedules[] = $schedule;
		}
	}

	rules_invoke_event('cowpro_fund_repayment_finished', TRUE, $node, $repayment_schedules);
 }
*/

//大额奖励报表
function cowpro_rewards_insert_issuing_large_data(){
    //上个月日期
   $rewards_date = date("Ym",mktime(0, 0 , 0,date("m")-1,1,date("Y")));
   $result = db_query("SELECT  f.amount as amount,i.field_issuing_loan_term as term,f.uid,f.issuing_id FROM {cowpro_fund_journal} as f LEFT JOIN {field_revision_field_issuing} as i ON f.issuing_id=i.entity_id WHERE f.type = 'BID' AND FROM_UNIXTIME( f.created, '%Y%m' ) = '".$rewards_date."' AND f.status =1 AND i.field_issuing_loan_term != 90")->fetchAll();
   $list = array();

   foreach( $result as $key=>$item ){
       $array = array();
       $array = get_object_vars($item);
       $list[$item->uid][$item->term][] = $array;
   }
   
    foreach( $list as $key=>$item ){
       foreach( $item as $_key=>$_item ){
            $total_amount = 0;
             foreach( $_item as $__key=>$__item ){
                 $total_amount += $__item['amount'];
             }
             foreach( $_item as $__key=>$__item ){
                 $list[$key][$_key][$__key]['total_amount'] = $total_amount;
             }
           
             if( $total_amount < 100000 ) {
                 unset($list[$key][$_key]);
             }
       }
       if( empty($list[$key][$_key]) ) {
            unset($list[$key]);
        }
   }

   foreach( $list as $key=>$item ){
       foreach( $item as $_key=>$_item ){
           foreach( $_item as $__key=>$__item ){
               if( $_key == 180 ) {
                    if( $__item['total_amount'] >= 100000 && $__item['total_amount'] < 200000 ) {
                        $rewards_rate = 10.44;
                        $rewards_level = 1;
                    }else if( $__item['total_amount'] >= 200000 && $__item['total_amount'] < 300000 ){
                        $rewards_rate = 10.92;
                        $rewards_level = 2;
                    }else if( $__item['total_amount'] >= 300000 && $__item['total_amount'] < 400000 ){
                        $rewards_rate = 11.40;
                        $rewards_level = 3;
                    }else if( $__item['total_amount'] >= 400000 && $__item['total_amount'] < 500000 ){
                        $rewards_rate = 11.64;
                        $rewards_level = 4;
                    }else if( $__item['total_amount'] >= 500000 ){
                        $rewards_rate = 11.88;
                        $rewards_level = 5;
                    }
                    $rewards_nominal = SIX_RATE;
                    $list[$key][$_key][$__key]['rewards_amount'] = ($rewards_rate - $rewards_nominal) / 100 * $__item['amount'] / ($_key / 30) / 2;
             
                }else if( $_key == 360 ){
                    if( $__item['total_amount'] >= 100000 && $__item['total_amount'] < 200000 ) {
                        $rewards_rate = 11.28;
                        $rewards_level = 1;
                    }else if( $__item['total_amount'] >= 200000 && $__item['total_amount'] < 300000 ){
                        $rewards_rate = 12.24;
                        $rewards_level = 2;
                    }else if( $__item['total_amount'] >= 300000 && $__item['total_amount'] < 400000 ){
                        $rewards_rate = 13.20;
                        $rewards_level = 3;
                    }else if( $__item['total_amount'] >= 400000 && $__item['total_amount'] < 500000 ){
                        $rewards_rate = 13.68;
                        $rewards_level = 4;
                    }else if( $__item['total_amount'] >= 500000 ){
                        $rewards_rate = 14.16;
                        $rewards_level = 5;
                    }
                    $rewards_nominal = TWELVE_RATE;
                    $list[$key][$_key][$__key]['rewards_amount'] = ($rewards_rate - $rewards_nominal) / 100 * $__item['amount'] / ($_key / 30);
                    
                }
                
                $list[$key][$_key][$__key]['rewards_level'] = $rewards_level;
           }
           
       }
   }

   $last_month_date =  db_query("SELECT * FROM {cowpro_rewards_issuing_large} WHERE issuing_date='".$rewards_date."'")->fetchAll();
   if( !$last_month_date ) {
    foreach( $list as $key=>$item ){
        foreach( $item as $_key=>$_item ){
            foreach( $_item as $__key=>$__item ){
                $count = $_key / 30;
                for( $i = 1; $i <= $count; $i++ ){
                 db_insert('cowpro_rewards_issuing_large')
                 ->fields(array(
                   'uid' => $__item['uid'],
                    'issuing_id' => $__item['issuing_id'],
                    'rewards_date' => date("Ym",mktime(0, 0 , 0,date("m")-1+$i,1,date("Y"))),
                    'rewards_amount' => $__item['rewards_amount'],
                    'rewards_level' => $__item['rewards_level'],
                     'issuing_date' => $rewards_date,
                     'created' => time(),
                   ))
                 ->execute();
                }
            }
        }
    }
   }
   
   global $base_url;
   drupal_goto($base_url."/cowpro_issuing_large");
}


/**
 * Implements hook_views_api().
 */
function cowpro_rewards_views_api() {
	return array (
			'api' => 3,
			'path' => drupal_get_path ( 'module', 'cowpro_rewards' ) . '/includes/views'
	);
}





