<?php

/**
 * Implementation of hook_menu()
 */
function rewards_menu() {
	$items ['cowpro/rewards/check_in'] = array (
			'title' => '签到',
			'description' => '',
			'page callback' => 'cowpro_rewards_check_in',
			'page arguments' => array (),
			'access callback' => 'user_is_logged_in',
			'type' => MENU_NORMAL_ITEM,
	);
	$items ['cowpro/rewards/employee_registration'] = array (
			'title' => '员工登记',
			'description' => '',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
				'cowpro_rewards_employee_registration_form',
			),
			'access arguments' => array('access user profiles'),
			'file' => 'includes/rewards.employee_registration.inc',
			'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function cowpro_rewards_check_in() {
	$uid = $GLOBALS ['user']->uid;
	if (cowpro_rewards_have_checked_in()) {
		drupal_set_message('您已经签过到了！', 'warning');
		drupal_goto();
		return;
	}

	db_merge('cowpro_rewards_checkin')
	->key(array('uid' => $uid))
	->fields(array(
			'uid' => $uid,
			'last_checkin' => time(),
	))
	->execute();

	$points = 1;
	$params = array (
			'uid' => $uid,
			'points' => $points,
			'description' => '签到奖励',
			'display' => FALSE,
			'tid' => 0,//积分
	);
	userpoints_userpointsapi($params);

	drupal_set_message('签到奖励积分1个！');
	drupal_goto();
	//return '欢迎签到';
}

function cowpro_rewards_have_checked_in() {
	$uid = $GLOBALS ['user']->uid;
	$start_time = mktime(0,0,0,date("n"),date("j"),date("Y"));//今天零时
	$query = db_select('cowpro_rewards_checkin', 'checkin')
	->fields('checkin', array('uid', 'last_checkin'))
	->condition('uid', $uid)
	->condition('last_checkin', $start_time, '>');

	if ($query->execute()->fetchObject()) {
		return TRUE;
	} else {
		return FALSE;
	}

}